[postgres]
host = "host_ip"
port = sql_port
dbname = "database_name"
user = "user_name"
password = "sql_password"

[bookmarks_path]
path = "path_to_chrome_bookmarks"
# On Mac: "/users/user/Library/Application Support/BraveSoftware/Brave-Browser/Default/Bookmarks"

[user_agent]
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"